version: '3'

services:
  influxdb:
    image: influxdb:2.7.5-alpine
    container_name: influxdb
    restart: unless-stopped
    volumes:
      - /influxdbv2/data:/var/lib/influxdb2:rw
      - /influxdbv2/config:/etc/influxdb2:rw
    ports:
      - "8086:8086"
    extra_hosts:
      - "host.docker.internal:host-gateway"
   #  telegraf:
        #image: telegraf:1.29.2-alpine
        #depends_on:
        #- influxdb
        #volumes:
        #- /telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
