version: '3'

services:
  influxdb:
    image: influxdb:2.7.5-alpine
    environment:
     - DOCKER_INFLUXDB_INIT_MODE=setup
    volumes:
      - /influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  #telegraf:
  #  image: telegraf:1.29.2-alpine
  #  depends_on:
  #    - influxdb
  #  volumes:
  #    - /telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
